### ISSUE TITLE
Hello, I want to reproduce the Fig. S13 in the supplemental materials using the theoretical results.

### ISSUE THREAD

**Issue by BaldStrong** [pjzuk/RepulsionSData#2]
Hello, I would like to reproduce the experimental results on repulsion in Fig.S13 using the theoretical results in the appendix, but I can't find the implementation in your paper.
![image](https://user-images.githubusercontent.com/37842039/172546285-fad1918b-dc1f-4d6d-8aa7-0e80c5deae3e.png)
I calculated the force per unit area through formula 78, I don't sure if the 'force acting on the wall' is acting on the electrode,and the result calculated by this formula is very different from what I expected.The calculated force oscillates periodically, but in fact it should gradually become stable.It takes about 15 minutes for the force to reach equilibrium in the experiment,but the numerical stability only needs 0.01s. Will the electric field change periodically with time after 15 minutes? 
![image](https://user-images.githubusercontent.com/37842039/172546933-24932484-2db0-499f-8664-f5ab27150dd7.png)

Looking forward to your help!😁

**Comment by pjzuk** [comment]
Hi, 
this is somewhat complex. But we will get through it. 
First,  the FIG. S13 is entirely experimental. It has not been plotted with any of my codes. It shows that there is a stationary state to be expected after time that is on the order of 10s of minutes. It was measured in prof. Carlos Drummond lab an simimlar results were obtained in prof. Susan Perikn lab.
Second, the formula 78 comes from the assumption that there is a hydrostatic situation ACROSS the gap. In 1D when we have a hydrostatic situation stress tensor in each position has to be the same. Therefore I chose place with coordinate x=1 because it contains explicitly the external pressure p(1) and  electric field E^2(1) and concentration at the center of the gap n(1).
Why it is important in the reasoning? It shows that in order to have excess force over the p(1) one needs either electric field that on average does not vanish across the channel and/or increase in ionic concentration. From the symmetry in the middle there cannot be  a non vanishing E present in the middle of the gap in the direction ACROSS. Therefore, if excess force is observed it must result from excess ions in the center that is also called the elevated osmotic pressure. 
That was our point in this contribution: why there is excess force? It must come from the excess ions being dragged into the gap. This sentence is the reason for all simulations and appendix.
Next, we used the 1D setup to show that there is similar dependence on the parameters in theory and experiment and we now knew where to look. We looked at the excess ionic concentrations in some place in the geometry. We chose at the wall because there it is the highest. And it agreed quite nice with what was measured to our surprise, which additionally supports the claim we made.
I hope this helps. 
Pawel
